// <auto-generated />
using EmployeeWebAPIService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeWebAPIService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeWebAPIService.Models.Employee", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AnnualSalary");

                    b.Property<string>("DateOfBirth");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.HasKey("Code");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Code = "emp101",
                            AnnualSalary = 5500.0,
                            DateOfBirth = "6/25/1988",
                            Gender = "Male",
                            Name = "Tom"
                        },
                        new
                        {
                            Code = "emp102",
                            AnnualSalary = 5700.9499999999998,
                            DateOfBirth = "9/6/1982",
                            Gender = "Male",
                            Name = "Alex"
                        },
                        new
                        {
                            Code = "emp103",
                            AnnualSalary = 5900.0,
                            DateOfBirth = "9/6/1982",
                            Gender = "Male",
                            Name = "Mike"
                        },
                        new
                        {
                            Code = "emp104",
                            AnnualSalary = 6500.826,
                            DateOfBirth = "10/14/1980",
                            Gender = "Female",
                            Name = "Mary"
                        },
                        new
                        {
                            Code = "emp105",
                            AnnualSalary = 6700.826,
                            DateOfBirth = "12/15/1982",
                            Gender = "Female",
                            Name = "Nancy"
                        },
                        new
                        {
                            Code = "emp106",
                            AnnualSalary = 7700.4809999999998,
                            DateOfBirth = "11/18/1979",
                            Gender = "Male",
                            Name = "Steve"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
